import { MARKETPLACE_BRIDGE_CHANNEL, MARKETPLACE_BRIDGE_VERSION, type MarketplaceBridgeApi } from "./marketplace-bridge";
import type { MarketplaceSkill } from "./skill-marketplace";

export function envelope(overrides: Record<string, unknown> = {}) {
  return {
    channel: MARKETPLACE_BRIDGE_CHANNEL,
    version: MARKETPLACE_BRIDGE_VERSION,
    type: "request",
    requestId: "req-1",
    method: "status",
    payload: {},
    ...overrides,
  };
}

export function trustedSkill(overrides: Partial<MarketplaceSkill> = {}): MarketplaceSkill {
  return {
    slug: "writing-helper",
    name: "Writing Helper",
    description: "Helpful",
    version: "1.2.3",
    version_id: "11111111-1111-4111-8111-111111111111",
    sha256: "a".repeat(64),
    resource: {
      schema_version: 1,
      id: "resource-1",
      version_id: "11111111-1111-4111-8111-111111111111",
      resource_type: "skill",
      slug: "writing-helper",
      display_name: "Writing Helper",
      summary: "Helpful",
      functional_category: "general",
      primary_locale: "und",
      tags: [],
      author: { id: null, name: "" },
      release: {
        version: "1.2.3",
        license: "MIT",
        release_notes: "",
        published_at: null,
        created_at: null,
        updated_at: null,
      },
      links: { repository_url: null, homepage_url: null, support_url: null },
      compatibility: {
        determinflow_requires: "*",
        required_tools: [],
        required_plugins: [],
        required_apps: [],
      },
      community: {
        download_count: 0,
        downloads_30d: 0,
        favorite_count: 0,
        rating_average: null,
        rating_count: 0,
        review_count: 0,
      },
      lifecycle: { deprecated_at: null, replacement_slug: null, deprecation_message: null },
    },
    payload: {
      type: "skill",
      name: "writing-helper",
      format_version: 1,
      sha256: "a".repeat(64),
      size_bytes: 12,
    },
    resource_type: "skill",
    license: "MIT",
    publisher_name: "社区贡献者",
    author_name: "",
    author_description: "",
    category: "general",
    functional_category: "general",
    primary_locale: "und",
    tags: [],
    determinflow_requires: "*",
    required_tools: [],
    required_plugins: [],
    required_apps: [],
    repository_url: null,
    homepage_url: null,
    support_url: null,
    release_notes: "",
    published_at: null,
    created_at: null,
    updated_at: null,
    download_count: 0,
    downloads_30d: 0,
    favorite_count: 0,
    rating_average: null,
    rating_count: 0,
    review_count: 0,
    deprecated_at: null,
    replacement_slug: null,
    deprecation_message: null,
    viewer: null,
    ...overrides,
  } as MarketplaceSkill;
}

export function fakeApi(overrides: Partial<MarketplaceBridgeApi> = {}): MarketplaceBridgeApi {
  const unused = async () => {
    throw new Error("unexpected API call");
  };
  return {
    fetchMarketplaceStatus: async () => ({ configured: true, signed_in: false, account_name: null, marketplace_url: "https://determinflow.com", embed_url: "https://determinflow.com/embed/marketplace", resource_types: ["skill", "prompt", "agent", "workflow", "rule"], publishable_resource_types: ["skill"], functional_categories: ["general", "novel", "comic-drama", "media", "development", "productivity", "business", "education", "other"] }),
    fetchMarketplaceSkills: unused as MarketplaceBridgeApi["fetchMarketplaceSkills"],
    fetchMarketplaceSkillPage: unused as MarketplaceBridgeApi["fetchMarketplaceSkillPage"],
    fetchMarketplaceSkill: unused as MarketplaceBridgeApi["fetchMarketplaceSkill"],
    previewMarketplaceSkill: unused as MarketplaceBridgeApi["previewMarketplaceSkill"],
    openInstalledMarketplaceSkill: unused as MarketplaceBridgeApi["openInstalledMarketplaceSkill"],
    fetchCommunityReviews: unused as MarketplaceBridgeApi["fetchCommunityReviews"],
    fetchCommunityReviewPage: unused as MarketplaceBridgeApi["fetchCommunityReviewPage"],
    setMarketplaceFavorite: unused as MarketplaceBridgeApi["setMarketplaceFavorite"],
    saveMarketplaceReview: unused as MarketplaceBridgeApi["saveMarketplaceReview"],
    deleteMarketplaceReview: unused as MarketplaceBridgeApi["deleteMarketplaceReview"],
    reportMarketplaceSkill: unused as MarketplaceBridgeApi["reportMarketplaceSkill"],
    reportMarketplaceReview: unused as MarketplaceBridgeApi["reportMarketplaceReview"],
    loginMarketplace: unused as MarketplaceBridgeApi["loginMarketplace"],
    logoutMarketplace: unused as MarketplaceBridgeApi["logoutMarketplace"],
    fetchEligibleLocalSkills: unused as MarketplaceBridgeApi["fetchEligibleLocalSkills"],
    previewLocalSkill: unused as MarketplaceBridgeApi["previewLocalSkill"],
    installMarketplaceSkill: unused as MarketplaceBridgeApi["installMarketplaceSkill"],
    updateMarketplaceSkill: unused as MarketplaceBridgeApi["updateMarketplaceSkill"],
    fetchMySubmissions: unused as MarketplaceBridgeApi["fetchMySubmissions"],
    publishMarketplaceSkill: unused as MarketplaceBridgeApi["publishMarketplaceSkill"],
    withdrawMarketplaceSubmission: unused as MarketplaceBridgeApi["withdrawMarketplaceSubmission"],
    resumeMarketplaceSkill: unused as MarketplaceBridgeApi["resumeMarketplaceSkill"],
    updateMarketplaceSkillLifecycle: unused as MarketplaceBridgeApi["updateMarketplaceSkillLifecycle"],
    listAuthorResources: unused as MarketplaceBridgeApi["listAuthorResources"],
    listAuthorVersions: unused as MarketplaceBridgeApi["listAuthorVersions"],
    listFeedback: unused as MarketplaceBridgeApi["listFeedback"],
    markFeedbackRead: unused as MarketplaceBridgeApi["markFeedbackRead"],
    getPublishDraft: unused as MarketplaceBridgeApi["getPublishDraft"],
    savePublishDraft: unused as MarketplaceBridgeApi["savePublishDraft"],
    deletePublishDraft: unused as MarketplaceBridgeApi["deletePublishDraft"],
    ...overrides,
  };
}
